/// Hive Types
const int HIVE_TYPE_USER_DATA_VO = 1;
const int HIVE_TYPE_BANNER_VO = 2;
const int HIVE_TYPE_MOVIE_VO = 3;
const int HIVE_TYPE_MOVIE_DETAIL_VO = 4;
const int HIVE_TYPE_ID_GENRE_VO = 5;
const int HIVE_TYPE_ID_ACTOR_VO = 6;
const int HIVE_TYPE_ID_TIME_SLOT_CONFIG_VO = 7;


/// Hive Box Names
const String BOX_NAME_USER_DATA_VO = "BOX_NAME_USER_DATA_VO";
const String BOX_NAME_BANNER_VO = "BOX_NAME_BANNER_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_MOVIE_DETAIL_VO = "BOX_NAME_MOVIE_DETAIL_VO";
const String BOX_NAME_TIME_SLOT_CONFIG_VO = "BOX_NAME_TIME_SLOT_CONFIG_VO";
